config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web' if Rails.env.development?

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    resource :session, only: %i[destroy]
    resources :repositories, only: %i[index show new create] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
      post 'invalidate_cache', on: :collection
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
end

app/views/layouts/shared/_nav.html.slim
.container.mb-2
  .d-flex.flex-wrap.align-items-center.py-2.border-bottom
    .navbar.navbar-expand-md.navbar-light.me-auto
      = link_to root_path, class: 'navbar-brand me-md-4' do
        = image_tag('logo.png', width: 30, alt: t('.hexlet_logo'))
      #navbarToggler.collapse.navbar-collapse
        ul.nav.nav-pills.flex-grow-1.navbar-nav.me-auto
          li.nav-item.me-2
            = link_to root_path, class: 'nav-link text-dark' do
              = t('.home')
          - if signed_in?
            li.nav-item.me-2
              = link_to repositories_path, class: 'nav-link text-dark' do
                = t('.repositories')
    ul.nav.nav-pills
      - if signed_in?
        li.nav-item.me-2
          = link_to root_path, class: 'nav-link text-secondary' do
            = current_user.email
        li.nav-item.me-2
          = link_to session_path, data: { turbo_method: :delete }, class: 'nav-link text-dark' do
            = t('.sign_out')
      - else
        li.nav-item.me-2
          = button_to auth_request_path('github'), data: { turbo: false }, class: 'nav-link text-dark'
            = t('.sign_in')