config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web' if Rails.env.development?

Rails.application.routes.draw do
  scope module: :web do
    root 'home#index'
    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    resource :session, only: %i[destroy]
    resources :repositories, only: %i[index show new create] do
      scope module: :repositories do
        resources :checks, only: %i[create show]
      end
      post 'invalidate_cache', on: :collection
    end
  end

  namespace :api do
    resources :checks, only: %i[create]
  end

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
end

app/models/repository.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repositories
#
#  id         :integer          not null, primary key
#  clone_url  :string
#  full_name  :string
#  language   :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  github_id  :integer
#  user_id    :integer          not null
#
# Indexes
#
#  index_repositories_on_github_id  (github_id) UNIQUE
#  index_repositories_on_user_id    (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Repository < ApplicationRecord
  extend Enumerize

  belongs_to :user, inverse_of: :repositories
  has_many :checks, class_name: 'Repository::Check', inverse_of: :repository, dependent: :destroy

  validates :github_id, presence: true, uniqueness: true

  enumerize :language, in: %i[javascript ruby], scope: true

  scope :by_id, -> { order(:id) }
end

app/models/repository/check.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repository_checks
#
#  id             :integer          not null, primary key
#  aasm_state     :string
#  offenses_count :integer          default(0)
#  passed         :boolean          default(FALSE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  commit_id      :string
#  repository_id  :integer          not null
#
# Indexes
#
#  index_repository_checks_on_repository_id  (repository_id)
#
# Foreign Keys
#
#  repository_id  (repository_id => repositories.id)
#
class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository, inverse_of: :checks, touch: true
  has_many :offenses, class_name: 'Repository::Offense', inverse_of: :check, dependent: :destroy

  aasm whiny_transitions: false do
    state :created, initial: true
    state :checking, :finished, :failed

    event :check do
      transitions from: :created, to: :checking
    end

    event :finish do
      transitions from: :checking, to: :finished
    end

    event :fail do
      transitions from: %i[created checking], to: :failed
    end
  end

  scope :by_id_desc, -> { order(id: :desc) }
end

app/models/repository/offense.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: repository_offenses
#
#  id         :integer          not null, primary key
#  coords     :string
#  message    :string
#  path       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  check_id   :integer          not null
#  rule_id    :string
#
# Indexes
#
#  index_repository_offenses_on_check_id  (check_id)
#
# Foreign Keys
#
#  check_id  (check_id => repository_checks.id)
#
class Repository::Offense < ApplicationRecord
  belongs_to :check, class_name: 'Repository::Check', inverse_of: :offenses, counter_cache: true
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

class Web::Repositories::ApplicationController < Web::ApplicationController
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::Repositories::ApplicationController
  before_action :authenticate_user!

  def show
    @repository = Repository.find(params[:repository_id])
    @check = @repository.checks.find(params[:id])
    authorize @check
    @offenses = @check.offenses.each_with_object({}) do |offense, acc|
      acc[offense.path] ||= []
      acc[offense.path] << offense
    end
  end

  def create
    @repository = Repository.find(params[:repository_id])
    authorize @repository, :check?
    @check = @repository.checks.build
    if @check.save
      CheckRepositoryJob.perform_later(@check.id)
      redirect_to repository_path(@repository), notice: t('.success')
    else
      redirect_to repository_path(@repository), alert: t('.failure')
    end
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < Web::ApplicationController
  before_action :authenticate_user!

  def index
    @repositories = current_user.repositories.by_id
  end

  def show
    @repository = Repository.find(params[:id])
    authorize @repository
  end

  def new
    @repositories_list = fetch_repositories_list
    @repository = Repository.new
    @cache_key = repositories_list_cache_key
  end

  def create
    @repository = current_user.repositories.find_or_initialize_by(repository_params)
    return redirect_to_repositories if @repository.persisted?

    if @repository.save
      process_new_repository
      redirect_to_repositories
    else
      flash.now[:failure] = t('.failure')
      @repositories_list = fetch_repositories_list
      @cache_key = repositories_list_cache_key
      render :new, status: :unprocessable_entity
    end
  end

  def invalidate_cache
    Rails.cache.delete(repositories_list_cache_key)
    redirect_to new_repository_path, notice: t('.success')
  end

  private

  def repository_params
    params.require(:repository).permit(:github_id)
  end

  def repositories_list_cache_key
    "repositories_list_#{current_user.token}"
  end

  def process_new_repository
    ProcessNewRepositoryJob.perform_later(@repository.id)
  end

  def fetch_repositories_list
    FetchRepositoriesListService.new(current_user.token).call
  end

  def redirect_to_repositories
    redirect_to repositories_path, notice: t('.success')
  end
end

app/views/web/repositories/_form.html.slim
= simple_form_for repository do |f|
  = f.error_notification
  - if f.object.errors[:base].present?
    = f.error_notification message: f.object.errors[:base].to_sentence

  = f.input :github_id, hint: false, as: :select, collection: repositories_list
  = f.submit t('buttons.create'), class: 'btn btn btn-success'

app/views/web/repositories/index.html.slim
- content_for :title do
  = t('.title')

.mb-4
  h1 = t('.title')
  br
  = link_to new_repository_path, class: 'btn btn-primary' do
    = t('.add')
  table.table.table-striped.table-hover.mt-4
    thead
      th[scope='col'] = t('.name')
      th[scope='col'] = t('.language')
      th[scope='col'] = t('.status')
    tbody
      - @repositories.each do |repository|
        tr
        td
          = link_to repository_path(repository) do
            = repository.name || t('.no_name')
        td = repository.language
        - check_passed = repository.checks.last&.passed
        td = check_passed.nil? ? t('was_not_checked') : check_passed

app/views/web/repositories/new.html.slim
- content_for :title do
  = t('.title')

.mb-4
  h1 = t('.title')
  br
  == render 'form', repository: @repository, repositories_list: @repositories_list.fetch(:repos)
  br
  - if Rails.cache.exist?(@cache_key)
    small = t('.last_update', period: time_ago_in_words(Time.zone.at(@repositories_list.fetch(:caching_time))))
    br
    small = t('.notice')
    br
    br
    = link_to invalidate_cache_repositories_path, data: { turbo_method: :post }, class: 'btn btn-outline-success btn-sm'
      = t('.invalidate_cache')

app/views/web/repositories/show.html.slim
- content_for :title do
  = t('.title')

.mb-4
  h1 = @repository.full_name
  br
  = link_to repository_checks_path(@repository), data: { turbo_method: :post }, class: 'btn btn-primary' do
    = t('.check')
  br
  br
  p
    strong.me-2 = t('.name')
    = @repository.full_name
  p
    strong.me-2 = t('.language')
    = @repository.language
  p
    strong.me-2 = t('.creating_date')
    = l(@repository.created_at, format: :long)
  p
    strong.me-2 = t('.updating_date')
    = l(@repository.updated_at, format: :long)
  hr
  - if @repository.checks.any?
    table.table.table-striped.mt-4
      thead
        tr
          th[scope='col'] = ''
          th[scope='col'] = t('.status')
          th[scope='col'] = t('.commit_id')
          th[scope='col'] = t('.check_passed')
          th[scope='col'] = t('.creating_date')
      tbody
        - @repository.checks.by_id_desc.each do |check|
          tr
          td
            = link_to repository_check_path(@repository, check) do
              = check.id
          td = check.aasm.human_state
          td = link_to github_commit_url(@repository, check.commit_id) do
            = check.commit_id
          td = check.passed
          td = l(check.created_at, format: :short)